import { useEffect, useMemo, useState } from "react";

const API_BASE = import.meta.env.VITE_API_URL;

function SecurityAlerts() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [severityFilter, setSeverityFilter] = useState("All");

  const fetchAlerts = async (showLoader = true) => {
    try {
      if (showLoader) setLoading(true);
      else setRefreshing(true);
      setError("");

      const token = localStorage.getItem("token");
      if (!token) throw new Error("Login session expired. Please login again.");

      const response = await fetch(`${API_BASE}/automation/alerts`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const contentType = response.headers.get("content-type") || "";
      const data = contentType.includes("application/json")
        ? await response.json()
        : { success: false, message: await response.text() };

      if (!response.ok || !data.success) {
        throw new Error(data.message || "Failed to fetch security alerts.");
      }

      setAlerts(Array.isArray(data.alerts) ? data.alerts : []);
    } catch (err) {
      console.error("FETCH ALERTS ERROR:", err);
      setError(err.message || "Server se security alerts fetch nahi ho pa rahe.");
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchAlerts(true);
    const interval = setInterval(() => fetchAlerts(false), 5000);
    return () => clearInterval(interval);
  }, []);

  const handleResolve = async (id) => {
    if (!id) return;

    try {
      setError("");
      const response = await fetch(`${API_BASE}/automation/alerts/${id}/resolve`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${localStorage.getItem("token") || ""}`,
        },
      });

      const contentType = response.headers.get("content-type") || "";
      const data = contentType.includes("application/json")
        ? await response.json()
        : { success: false, message: await response.text() };

      if (!response.ok || !data.success) {
        throw new Error(data.message || "Alert resolve failed.");
      }

      await fetchAlerts(false);
    } catch (err) {
      console.error("RESOLVE ALERT ERROR:", err);
      setError(err.message || "Alert resolve nahi ho saka.");
    }
  };

  const formatDateTime = (value) => {
    if (!value) return "-";
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return "-";
    return date.toLocaleString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  const totalAlerts = alerts.length;
  const activeAlerts = alerts.filter((alert) => alert.status === "Active").length;
  const resolvedAlerts = alerts.filter((alert) => alert.status === "Resolved").length;
  const highAlerts = alerts.filter((alert) => (alert.severity || "Medium") === "High").length;

  const filteredAlerts = useMemo(() => {
    const query = search.trim().toLowerCase();

    return alerts.filter((alert) => {
      const matchesSearch =
        !query ||
        [alert.type, alert.vehicleNumber, alert.location, alert.message]
          .some((value) => String(value || "").toLowerCase().includes(query));

      const matchesStatus =
        statusFilter === "All" || (alert.status || "Active") === statusFilter;

      const matchesSeverity =
        severityFilter === "All" || (alert.severity || "Medium") === severityFilter;

      return matchesSearch && matchesStatus && matchesSeverity;
    });
  }, [alerts, search, statusFilter, severityFilter]);

  const getAlertMeta = (type) => {
    if (type === "Unauthorized Vehicle") {
      return { icon: "!", label: "Vehicle Security", tone: "danger" };
    }
    if (type === "Camera Offline") {
      return { icon: "◉", label: "Camera Monitoring", tone: "warning" };
    }
    if (type === "Parking Violation") {
      return { icon: "P", label: "Parking Security", tone: "warning" };
    }
    return { icon: "!", label: "Security Monitoring", tone: "info" };
  };

  const clearFilters = () => {
    setSearch("");
    setStatusFilter("All");
    setSeverityFilter("All");
  };

  return (
    <div className="security-alerts-page" style={styles.page}>
      <div style={styles.container}>
        {/* PAGE TITLE */}
        <section style={styles.hero}>
          <div>
            <div style={styles.kicker}>CAMPUS SECURITY ALERTS</div>
            <h1 style={styles.title}>Security Alerts</h1>
            <p style={styles.subtitle}>
              Monitor unauthorized vehicles and security events generated by the live campus surveillance system.
            </p>
          </div>
          <button
            type="button"
            onClick={() => fetchAlerts(false)}
            disabled={refreshing}
            style={styles.refreshButton}
          >
            <span style={{ fontSize: 17 }}>↻</span>
            {refreshing ? "Refreshing..." : "Refresh"}
          </button>
        </section>

        {error && (
          <div style={styles.errorBox}>
            <strong>Unable to load alerts</strong>
            <span>{error}</span>
          </div>
        )}

        {/* KPI CARDS */}
        <section className="alerts-kpi-grid" style={styles.statsGrid}>
          <StatCard icon="!" label="Total Alerts" value={totalAlerts} note="All recorded alerts" tone="danger" />
          <StatCard icon="●" label="Active Alerts" value={activeAlerts} note="Require attention" tone="active" />
          <StatCard icon="✓" label="Resolved Alerts" value={resolvedAlerts} note="Successfully closed" tone="success" />
          <StatCard icon="H" label="High Priority" value={highAlerts} note="High severity alerts" tone="high" />
        </section>

        {/* ALERT LIST */}
        <section style={styles.panel}>
          <div className="alerts-panel-header" style={styles.panelHeader}>
            <div>
              <div style={styles.panelKicker}>LIVE SECURITY FEED</div>
              <h2 style={styles.panelTitle}>Recent Security Alerts</h2>
              <p style={styles.panelSubtitle}>Latest alerts generated by the campus monitoring system.</p>
            </div>
            <div style={styles.countBadge}>
              {loading ? "Loading..." : `${filteredAlerts.length} of ${alerts.length}`}
            </div>
          </div>

          <div className="alerts-filter-bar" style={styles.filterBar}>
            <div style={styles.searchWrap}>
              <span style={styles.searchIcon}>⌕</span>
              <input
                type="search"
                value={search}
                onChange={(event) => setSearch(event.target.value)}
                placeholder="Search vehicle, alert type, location..."
                style={styles.searchInput}
                aria-label="Search security alerts"
              />
            </div>

            <select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)} style={styles.select}>
              <option value="All">All Status</option>
              <option value="Active">Active</option>
              <option value="Resolved">Resolved</option>
            </select>

            <select value={severityFilter} onChange={(event) => setSeverityFilter(event.target.value)} style={styles.select}>
              <option value="All">All Priority</option>
              <option value="High">High</option>
              <option value="Medium">Medium</option>
              <option value="Low">Low</option>
            </select>

            {(search || statusFilter !== "All" || severityFilter !== "All") && (
              <button type="button" onClick={clearFilters} style={styles.clearButton}>
                Clear
              </button>
            )}
          </div>

          {loading ? (
            <div style={styles.emptyState}>
              <div style={styles.loaderCircle}>↻</div>
              <strong>Loading security alerts...</strong>
              <span>Fetching the latest records from the monitoring server.</span>
            </div>
          ) : filteredAlerts.length === 0 ? (
            <div style={styles.emptyState}>
              <div style={styles.successCircle}>✓</div>
              <strong>{alerts.length === 0 ? "No Security Alerts" : "No Matching Alerts"}</strong>
              <span>
                {alerts.length === 0
                  ? "No alerts have been generated yet."
                  : "Try changing your search or filters."}
              </span>
            </div>
          ) : (
            <div style={styles.alertList}>
              {filteredAlerts.map((alert, index) => {
                const meta = getAlertMeta(alert.type);
                const isResolved = alert.status === "Resolved";
                const severity = alert.severity || "Medium";

                return (
                  <article className="alerts-alert-row" key={alert._id || `${alert.vehicleNumber}-${index}`} style={styles.alertRow}>
                    <div style={{ ...styles.alertIcon, ...toneStyles[meta.tone] }}>
                      {meta.icon}
                    </div>

                    <div className="alerts-alert-content" style={styles.alertContent}>
                      <div className="alerts-alert-top-line" style={styles.alertTopLine}>
                        <div>
                          <div style={styles.alertType}>{alert.type || "Security Alert"}</div>
                          <div style={styles.alertCategory}>{meta.label}</div>
                        </div>
                        <div className="alerts-badge-group" style={styles.badgeGroup}>
                          <span style={{ ...styles.priorityBadge, ...priorityStyles[severity] }}>
                            {severity} Priority
                          </span>
                          <span style={{ ...styles.statusBadge, ...(isResolved ? styles.resolvedBadge : styles.activeBadge) }}>
                            {alert.status || "Active"}
                          </span>
                        </div>
                      </div>

                      <div className="alerts-alert-details" style={styles.alertDetailsGrid}>
                        <Detail label="Vehicle Number" value={alert.vehicleNumber || "Unknown"} strong />
                        <Detail label="Location" value={alert.location || "Main Gate"} />
                        <Detail label="Detected" value={formatDateTime(alert.detectedAt || alert.createdAt)} />
                      </div>

                      <div style={styles.messageBox}>
                        <span>{alert.message || "Security alert generated by the monitoring system."}</span>
                      </div>
                    </div>

                    <div className="alerts-alert-action" style={styles.alertAction}>
                      {isResolved ? (
                        <div style={styles.resolvedText}>✓ Resolved</div>
                      ) : (
                        <button
                          type="button"
                          onClick={() => handleResolve(alert._id)}
                          style={styles.resolveButton}
                        >
                          ✓ Resolve
                        </button>
                      )}
                    </div>
                  </article>
                );
              })}
            </div>
          )}
        </section>

        <section className="alerts-info-strip" style={styles.infoStrip}>
          <div>
            <strong>Dr. C. V. Raman University</strong>
            <span>Vaishali, Bihar • Campus Surveillance System</span>
          </div>
          <span>Live security data • Automatic monitoring • 5-second refresh</span>
        </section>
      </div>

      <style>{`
        .security-alerts-page * { box-sizing: border-box; }
        .security-alerts-page button, .security-alerts-page input, .security-alerts-page select { font: inherit; }
        @media (max-width: 1050px) {
          .alerts-responsive-grid { grid-template-columns: repeat(2, minmax(0, 1fr)) !important; }
        }
        @media (max-width: 760px) {
          .alerts-responsive-grid { grid-template-columns: 1fr !important; }
          .alerts-filter-responsive { grid-template-columns: 1fr !important; }
          .alerts-row-responsive { flex-direction: column !important; }
        }
      `}</style>
    </div>
  );
}

function StatCard({ icon, label, value, note, tone }) {
  return (
    <article style={styles.statCard}>
      <div style={{ ...styles.statIcon, ...toneStyles[tone] }}>{icon}</div>
      <div style={styles.statBody}>
        <span style={styles.statLabel}>{label}</span>
        <strong style={styles.statValue}>{value}</strong>
        <span style={styles.statNote}>{note}</span>
      </div>
      <div style={{ ...styles.statLine, ...lineStyles[tone] }} />
    </article>
  );
}

function Detail({ label, value, strong = false }) {
  return (
    <div style={styles.detailItem}>
      <span style={styles.detailLabel}>{label}</span>
      <strong style={strong ? styles.vehicleValue : styles.detailValue}>{value}</strong>
    </div>
  );
}

const toneStyles = {
  danger: { background: "#fff0f1", color: "#dc2626" },
  active: { background: "#fff7e8", color: "#d97706" },
  success: { background: "#eaf9f1", color: "#059669" },
  high: { background: "#eef3ff", color: "#2563eb" },
  warning: { background: "#fff7e8", color: "#d97706" },
  info: { background: "#eef5ff", color: "#2563eb" },
};

const priorityStyles = {
  High: { background: "#ffe4e6", color: "#be123c", border: "1px solid #fecdd3" },
  Medium: { background: "#fff7ed", color: "#c2410c", border: "1px solid #fed7aa" },
  Low: { background: "#eff6ff", color: "#1d4ed8", border: "1px solid #bfdbfe" },
};

const lineStyles = {
  danger: { background: "#ef4444" },
  active: { background: "#f59e0b" },
  success: { background: "#10b981" },
  high: { background: "#3b82f6" },
};

const styles = {
  page: {
    minHeight: "100%",
    background: "#f4f7fb",
    padding: "26px 28px 34px",
    color: "#0b315c",
    fontFamily: "Inter, Segoe UI, Arial, sans-serif",
  },
  container: { width: "100%", maxWidth: 1480, margin: "0 auto" },
  brandCard: {
    background: "#ffffff",
    border: "1px solid #dce7f3",
    borderRadius: 16,
    padding: "15px 20px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 20,
    marginBottom: 18,
    boxShadow: "0 5px 18px rgba(15, 55, 95, 0.06)",
  },
  brandLeft: { display: "flex", alignItems: "center", gap: 15 },
  logoBox: {
    width: 76,
    height: 62,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: 10,
    background: "#fff",
  },
  logo: { width: "100%", height: "100%", objectFit: "contain" },
  brandUniversity: { fontWeight: 800, fontSize: 17, letterSpacing: "0.3px", color: "#082b52" },
  brandLocation: { marginTop: 3, fontSize: 12, fontWeight: 700, color: "#507091", letterSpacing: "1px" },
  brandRight: { display: "flex", alignItems: "center", gap: 8, color: "#55718f", fontSize: 12, whiteSpace: "nowrap" },
  liveDot: { width: 9, height: 9, borderRadius: "50%", background: "#18b978", boxShadow: "0 0 0 4px #e5f8ef" },
  hero: {
    position: "relative",
    overflow: "hidden",
    backgroundImage: "linear-gradient(90deg, rgba(5,39,76,.94) 0%, rgba(7,58,103,.78) 48%, rgba(8,57,96,.35) 100%), url('/cvru-campus.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: 18,
    minHeight: 180,
    padding: "30px 34px",
    color: "#fff",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 24,
    marginBottom: 18,
    boxShadow: "0 12px 28px rgba(8,43,82,.16)",
  },
  kicker: { fontSize: 10, fontWeight: 800, letterSpacing: "1.4px", color: "#a9d7ff", marginBottom: 7 },
  title: { margin: 0, fontSize: 30, lineHeight: 1.15, letterSpacing: "-.5px" },
  subtitle: { margin: "8px 0 0", maxWidth: 780, fontSize: 13, lineHeight: 1.55, color: "#dcecff" },
  refreshButton: {
    border: "1px solid rgba(255,255,255,.35)",
    background: "#fff",
    color: "#0b4e91",
    borderRadius: 10,
    padding: "11px 17px",
    fontWeight: 800,
    cursor: "pointer",
    minWidth: 108,
  },
  errorBox: {
    background: "#fff1f2",
    border: "1px solid #fecdd3",
    color: "#9f1239",
    borderRadius: 12,
    padding: "12px 16px",
    marginBottom: 18,
    display: "flex",
    flexDirection: "column",
    gap: 3,
    fontSize: 13,
  },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0,1fr))", gap: 15, marginBottom: 18 },
  statCard: {
    position: "relative",
    overflow: "hidden",
    background: "#fff",
    border: "1px solid #dce7f3",
    borderRadius: 15,
    padding: "18px 19px 21px",
    minHeight: 126,
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    boxShadow: "0 5px 16px rgba(15,55,95,.05)",
  },
  statIcon: { width: 43, height: 43, borderRadius: 12, display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 900, fontSize: 19, flex: "0 0 auto" },
  statBody: { display: "flex", flexDirection: "column", gap: 3 },
  statLabel: { fontSize: 12, color: "#58718d", fontWeight: 700 },
  statValue: { fontSize: 29, lineHeight: 1.05, color: "#0b315c", letterSpacing: "-.5px" },
  statNote: { fontSize: 11, color: "#8094aa", marginTop: 2 },
  statLine: { position: "absolute", left: 0, right: 0, bottom: 0, height: 3, opacity: .8 },
  panel: { background: "#fff", border: "1px solid #dce7f3", borderRadius: 17, boxShadow: "0 6px 20px rgba(15,55,95,.06)", overflow: "hidden" },
  panelHeader: { padding: "22px 23px 18px", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 20, borderBottom: "1px solid #edf2f7" },
  panelKicker: { fontSize: 10, fontWeight: 800, letterSpacing: "1.3px", color: "#2770bd", marginBottom: 5 },
  panelTitle: { margin: 0, color: "#0b315c", fontSize: 21 },
  panelSubtitle: { margin: "5px 0 0", color: "#6d8198", fontSize: 12.5 },
  countBadge: { background: "#eef5ff", color: "#1e5fa7", border: "1px solid #d7e7fb", borderRadius: 20, padding: "7px 11px", fontSize: 11, fontWeight: 800, whiteSpace: "nowrap" },
  filterBar: { padding: "15px 23px", background: "#fbfcfe", borderBottom: "1px solid #edf2f7", display: "flex", gap: 9, alignItems: "center", flexWrap: "wrap" },
  searchWrap: { flex: "1 1 340px", minWidth: 220, position: "relative" },
  searchIcon: { position: "absolute", left: 12, top: 9, color: "#71869e", fontSize: 19 },
  searchInput: { width: "100%", height: 38, border: "1px solid #cddceb", borderRadius: 9, padding: "0 12px 0 34px", outline: "none", color: "#173e67", background: "#fff" },
  select: { height: 38, minWidth: 145, border: "1px solid #cddceb", borderRadius: 9, padding: "0 11px", background: "#fff", color: "#294d70", outline: "none" },
  clearButton: { height: 38, border: "1px solid #cddceb", borderRadius: 9, background: "#fff", color: "#1d5e9d", fontWeight: 700, padding: "0 13px", cursor: "pointer" },
  emptyState: { minHeight: 250, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 7, color: "#6d8198", textAlign: "center", padding: 30 },
  loaderCircle: { width: 48, height: 48, borderRadius: "50%", background: "#eef5ff", color: "#2468ad", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 25, marginBottom: 5 },
  successCircle: { width: 48, height: 48, borderRadius: "50%", background: "#eaf9f1", color: "#059669", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 23, marginBottom: 5 },
  alertList: { display: "flex", flexDirection: "column" },
  alertRow: { display: "grid", gridTemplateColumns: "52px minmax(0,1fr) auto", gap: 16, padding: "19px 23px", borderBottom: "1px solid #edf2f7", alignItems: "start" },
  alertIcon: { width: 46, height: 46, borderRadius: 13, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, fontWeight: 900 },
  alertContent: { minWidth: 0 },
  alertTopLine: { display: "flex", justifyContent: "space-between", gap: 15, alignItems: "flex-start" },
  alertType: { color: "#102f54", fontSize: 16, fontWeight: 800 },
  alertCategory: { color: "#8396aa", fontSize: 10.5, marginTop: 3, fontWeight: 700, textTransform: "uppercase", letterSpacing: ".7px" },
  badgeGroup: { display: "flex", gap: 6, flexWrap: "wrap", justifyContent: "flex-end" },
  priorityBadge: { borderRadius: 20, padding: "5px 9px", fontSize: 10, fontWeight: 800, whiteSpace: "nowrap" },
  statusBadge: { borderRadius: 20, padding: "5px 9px", fontSize: 10, fontWeight: 800, whiteSpace: "nowrap" },
  activeBadge: { background: "#fff1f2", color: "#be123c", border: "1px solid #fecdd3" },
  resolvedBadge: { background: "#eaf9f1", color: "#047857", border: "1px solid #bbf7d0" },
  alertDetailsGrid: { display: "grid", gridTemplateColumns: "minmax(170px,1.3fr) minmax(150px,1fr) minmax(190px,1fr)", gap: 10, marginTop: 14 },
  detailItem: { background: "#f8fafc", border: "1px solid #e8eef5", borderRadius: 9, padding: "8px 10px", display: "flex", flexDirection: "column", gap: 2 },
  detailLabel: { fontSize: 9.5, color: "#8193a7", textTransform: "uppercase", letterSpacing: ".7px", fontWeight: 800 },
  detailValue: { fontSize: 12, color: "#385a79" },
  vehicleValue: { fontSize: 14, color: "#102f54", letterSpacing: "1px" },
  messageBox: { marginTop: 9, color: "#61778f", fontSize: 12, lineHeight: 1.45 },
  alertAction: { minWidth: 94, display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 10 },
  resolveButton: { border: "1px solid #b9d8c9", background: "#effbf5", color: "#047857", borderRadius: 9, padding: "9px 12px", fontWeight: 800, fontSize: 11, cursor: "pointer" },
  resolvedText: { color: "#047857", fontSize: 11, fontWeight: 800, paddingTop: 8 },
  infoStrip: { marginTop: 16, background: "#082b52", color: "#fff", borderRadius: 14, padding: "15px 19px", display: "flex", justifyContent: "space-between", gap: 20, alignItems: "center", fontSize: 11 },
};

export default SecurityAlerts;
